### ISSUE TITLE
Several processes still running in background.

### ISSUE THREAD

**Issue by fgomes-anywind** [dmazz55/Pdfvert#1]
After converting an excel file to pdf, soffice.exe and soffice.bin processes still run in background.
After converting some more files, there are more processes soffice.exe and soffice.bin running in background.

At some point i cannot anymore convert files unless i kill processes running in the background.

It seems to me that the processes are not being shutdown after the file conversion.

Error:
Starting Open Office...
...Getting a ComponentContext

Unhandled Exception: System.Runtime.InteropServices.SEHException: External compo
nent has thrown an exception.
   at cppu.bootstrap(Reference<com::sun::star::uno::XComponentContext>* )
   at uno.util.Bootstrap.bootstrap()
   at Pdfvert.Core.Utilities.OpenOfficeUtility.GetComponentContext()
   at Pdfvert.Core.PdfvertService.ConvertFileToPdf(String inputFile, String outp
utFile)
   at ConsoleApplication1.Program.Main(String[] args)

**Comment by shekharsom** [comment]
I downloaded the library, modified this section 

`var ps = Process.GetProcessesByName("soffice.exe");
if (ps.Length != 0) throw new InvalidProgramException("Do you even OpenOffice bro? - OpenOffice not found. Is it installed?");
if (ps.Length > 0) return;`

to 

`var ps = Process.GetProcessesByName("soffice");
//if (ps.Length != 0) throw new InvalidProgramException("Do you even OpenOffice bro? - OpenOffice not found. Is it installed?");
if (ps.Length > 0) return;`

This cleared the problem.

**Comment by dmazz55** [comment]
Updated. Thank you for reporting this.
